//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.TicTacToe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.Kinect.TicTacToe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME ENDED IN A DRAW.
        /// </summary>
        internal static string GameDraw {
            get {
                return ResourceManager.GetString("GameDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Board index.
        /// </summary>
        internal static string InvalidBoardIndex {
            get {
                return ResourceManager.GetString("InvalidBoardIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to place symbol in an invalid square.
        /// </summary>
        internal static string InvalidPlacingSquare {
            get {
                return ResourceManager.GetString("InvalidPlacingSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQUARE PLAYED MUST NOT BE OCCUPIED.
        /// </summary>
        internal static string OccupiedSquare {
            get {
                return ResourceManager.GetString("OccupiedSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER O, SAY A NUMBER.
        /// </summary>
        internal static string OSayNumber {
            get {
                return ResourceManager.GetString("OSayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT&apos;S &quot;O&apos;s&quot; TURN.
        /// </summary>
        internal static string OTurn {
            get {
                return ResourceManager.GetString("OTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O WON!.
        /// </summary>
        internal static string OWon {
            get {
                return ResourceManager.GetString("OWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grammar version=&quot;1.0&quot; xml:lang=&quot;en-US&quot; tag-format=&quot;semantics/1.0-literals&quot; xmlns=&quot;http://www.w3.org/2001/06/grammar&quot;&gt;
        ///  &lt;rule id=&quot;welcomeRule&quot; scope=&quot;public&quot;&gt;
        ///    &lt;one-of&gt;
        ///      &lt;item&gt;
        ///        &lt;tag&gt;START&lt;/tag&gt;
        ///        &lt;one-of&gt;
        ///          &lt;item&gt;start&lt;/item&gt;
        ///          &lt;item&gt;start game&lt;/item&gt;
        ///        &lt;/one-of&gt;
        ///      &lt;/item&gt;
        ///    &lt;/one-of&gt;
        ///  &lt;/rule&gt;
        ///  &lt;rule id=&quot;gameRule&quot; scope=&quot;public&quot;&gt;
        ///    &lt;one-of&gt;
        ///      &lt;item&gt;
        ///        &lt;tag&gt;CHEATENABLE&lt;/tag&gt;
        ///        &lt;one-of&gt;
        ///          &lt;item&gt;enable cheat&lt;/item&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpeechGrammar {
            get {
                return ResourceManager.GetString("SpeechGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITING FOR PLAYERS....
        /// </summary>
        internal static string WaitingForPlayers {
            get {
                return ResourceManager.GetString("WaitingForPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITING FOR SECOND PLAYER....
        /// </summary>
        internal static string WaitingForSecondPlayer {
            get {
                return ResourceManager.GetString("WaitingForSecondPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAY A NUMBER FROM 1 THROUGH 9.
        /// </summary>
        internal static string WrongNumber {
            get {
                return ResourceManager.GetString("WrongNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER X, SAY A NUMBER.
        /// </summary>
        internal static string XSayNumber {
            get {
                return ResourceManager.GetString("XSayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT&apos;S &quot;X&apos;s&quot; TURN.
        /// </summary>
        internal static string XTurn {
            get {
                return ResourceManager.GetString("XTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X WON!.
        /// </summary>
        internal static string XWon {
            get {
                return ResourceManager.GetString("XWon", resourceCulture);
            }
        }
    }
}
